favicon: null
name: GraceWorship
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5
  brandStrength: 1
  rhythmicContrast: 0.3677608806174248
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  lightness: 0.625
typography_spectrum: 0.35054
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.2473118
analytics:
  twitter: null
  google: null
  facebook: null
