name: GraceWorship
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35054
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.36776088061742485
purpose: []
