typography_spectrum: 0.3691756
color:
  saturation: 0.6875
  brandStrength: 0.8125
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  lightness: 0.625
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3225806
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Rodney Gehman
  email: rodneyg@graceb3.org
  url: www.facebook.com/rjgehman
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94625673-7ff7-4750-954a-2e8d82cbe4c0.jpg
name: Grace Worship
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - id: a3ecb426-7718-4725-b3b5-6ceee2176b4c
    url: 2016-06-29-june.html
    name: YouTube Videos
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Music Ministry
purpose: []
