name: Grace Worship
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33138
title: Grace Community Church // Music Ministry
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
