typography_spectrum: 0.8136201
color:
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  brandStrength: 0.327957
  lightness: 1
  saturation: 0.4247312
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74069
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: RODNEY GEHMAN
  email: rodneyg@graceb3.org
  url: www.facebook.com/rjgehman
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94625673-7ff7-4750-954a-2e8d82cbe4c0.jpg
name: Grace Worship
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Music Ministry
purpose: []
