title: Grace Community Church // Music Ministry
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4247312
  brandStrength: 0.327957
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Grace Worship
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8136201
layout_spectrum: 0.5286738
