typography_spectrum: 0.771148587577045
color:
  saturation: 0.6875
  brandStrength: 0.8125
  rhythmicContrast: 0.25
  brandColors:
    - '#ffffff'
    - '#3c2d18'
    - '#026536'
    - '#8cc63e'
    - '#959088'
  lightness: 0.625
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03647570824250579
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Rodney Gehman
  email: rodneyg@graceb3.org
  url: www.facebook.com/rjgehman
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94625673-7ff7-4750-954a-2e8d82cbe4c0.jpg
name: Grace Worship
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Twitter
    url: 'http://www.twitter.com/graceworship'
    type: external
  - name: Facebook
    url: 'http://www.facebook.com/gracenorthliberty'
    type: external
  - name: Team Night
    id: 4450ef07-f3e9-4346-aa32-ebafa0ad84f4
    type: content
  - name: Sunday Set List Videos
    id: 26c93d39-9fea-4daf-8fe7-c4cc4fc18ccc
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Music Ministry
description: 'Psalms, Hymns, and Spiritual Songs for Grace Community Church'
purpose: []
